            <div id="footer" class="grid_12">
                <ul class="menu">
                    <li><a href="">About TM Secure</a></li>
                    <li><a href="">Contact Us</a></li>
                    <li><a href="">Terms of Service</a></li>
                    <li><a href="">Privacy</a></li>
                </ul>
                <p>©2010 TM Secure LLC +1 (408) 400-3658</p>
            </div>
            <div class="clear">&nbsp;</div> 
