<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo(($this->jQuery()->isEnabled())?$this->jQuery():''); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div id="tmsecure-wrapper" class="container container_12">
            <?php echo $this->render('_header.phtml'); ?>
            <div id="tmsecure-content-wrapper" class="shadow">
                <div class="grid_8">
                    <div class="content"><?php echo $this->layout()->content; ?></div>
                </div>
                <div class="grid_4">
                    <div class="content"><?php echo $this->render('_sidebar.phtml'); ?></div>
                </div>                
                <div class="clear">&nbsp;</div>
            </div>
            <?php echo $this->render('_footer.phtml'); ?>
        </div>        
    </body>
</html>